version: '3'

services:
  db:
    image: mysql:8.0.21
    container_name: db
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

  backend:
    image: node:16.14-alpine
    container_name: app_backend
    tty: true
    stdin_open: true
    ports:
      - 3001:3001
    working_dir: /app-backend
    command: npm run dev
    restart: always
    volumes:
      - ./back-end:/app-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT: 3001
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      DATABASE_NAME: delivery-app
      MYSQL_USER: root
      MYSQL_PASSWORD: password

  frontend:
    image: node:16.14-alpine
    container_name: app_frontend
    ports:
      - 3000:3000
    working_dir: /app-frontend
    command: npm start
    restart: always
    volumes:
      - ./front-end:/app-frontend
    depends_on:
      - backend
    environment:
      REACT_APP_HOSTNAME: localhost
      REACT_APP_BACKEND_PORT: 3001

networks:
  default:
    name: appDelivery_net